### ISSUE TITLE
Feature Validation - error message should say that type must be "Feature" not "feature"

### ISSUE THREAD

**Issue by ozomer** [craveprogramminginc/GeoJSON-Validation#6]
Just copy-pasted the second example and got an error message:`type must be 'feature'`.
Took me some time to figure out what the error is...

**Comment by wanderer** [comment]
what would a better message be?

**Comment by ozomer** [comment]
Feature with capital F.

**Comment by wanderer** [comment]
should be fix in [0.2](https://github.com/craveprogramminginc/GeoJSON-Validation/tree/v0.2.0)
